### ISSUE TITLE
Design The Cost function

### ISSUE THREAD

**Issue by sezan92** [sezan92/CarND-Path-Planning-Project#2]
## Objective 
Ref: #1 

The objective is to design the cost function for given state trajectory

### Tasks
- [x]  Determine the goals
- [ ]  Measure the speed cost
- [x]  Determine the collision cost
- [x]  Determine the lane change cost
- [x] Add them and predict the total cost
